# Generated by Django 4.2.28 on 2026-02-11 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STARTED', 'Started'), ('ENDED', 'Ended')], default='CREATED', max_length=10)),
                ('start_trip_at', models.DateTimeField(blank=True, null=True)),
                ('end_trip_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route')),
            ],
        ),
    ]
