# Generated by Django 6.0.1 on 2026-02-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_bus_id_alter_organization_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
